<h2 class = "login-heading">Вхід до системи</h2>
<form action="index.php?action=login" method="post" class="login-form">
    <div>
        <label for="username">Ім'я користувача:</label>
        <input type="text" id="username" name="username" required autofocus>
    </div>
    <div>
        <label for="password">Пароль:</label>
        <input type="password" id="password" name="password" required>
    </div>
    <button type="submit">Увійти</button>
</form>
